### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by jatinagg1**

### CODE REVIEW

**Comment by arush15june** [comment]
Add your information to index.html

**Comment by kautukkundan** [comment]
fix the changes asap!

**Comment by jatinagg1** [comment]
Okay I will try asap

**Comment by kautukkundan** [comment]
pull changes from upstream
1. add name in contributors.md
2. MAKE CHANGES IN INDEX DOT HTML!

**Comment by jatinagg1** [comment]
i have already added my name and everything in contributers.md
also i have added my profile page in the profiles folder
and i have too writeen and entered my code of hello world in the scripts
folder.

These were the only steps mentioned in the readme file that were to be done.

**Comment by jatinagg1** [comment]
sorry i got confused between two hacktoberfest repositories...i am just now
making the reqd. changes

**Pull request merged**
